# Generated by Django 5.2.4 on 2025-08-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=150)),
                ('des', models.TextField()),
                ('image', models.ImageField(upload_to='car_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('band_name', models.ManyToManyField(to='bands.bands')),
            ],
        ),
    ]
