# Generated by Django 5.2.4 on 2025-08-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='band_name',
        ),
    ]
