# Generated by Django 5.2.4 on 2025-08-12 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_remove_bands_car_name'),
        ('cars', '0002_remove_cars_band_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='band',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bands.bands'),
            preserve_default=False,
        ),
    ]
