# Generated by Django 5.2.4 on 2025-08-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
