# Generated by Django 5.2.4 on 2025-08-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
        ('cars', '0002_remove_cars_band_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bands',
            name='car_name',
            field=models.ManyToManyField(to='cars.cars'),
        ),
    ]
