# Generated by Django 5.2.4 on 2025-08-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_bands_car_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bands',
            name='car_name',
        ),
    ]
