# Generated by Django 5.2.4 on 2025-08-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_remove_bands_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bands',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
